# JupyterLite で学ぶ NumPy 初級チュートリアル

このノートブックは、**JupyterLite（ブラウザだけで動く Jupyter 環境）** 上で、
Python の数値計算ライブラリ **NumPy** の基礎を一から学ぶためのチュートリアルです。

## 対象者
- Python の基本（変数、リスト、ループなど）を理解している方
- NumPy を初めて使う方、または基礎を復習したい方

## このチュートリアルで学ぶこと
1. NumPy とは何か
2. 配列（ndarray）の作成
3. 配列の属性
4. インデックスとスライス
5. 配列の演算
6. ユニバーサル関数
7. 基本的な統計関数
8. 配列の形状操作

## 0. 環境準備（JupyterLite 用）

まず、必要なライブラリをインストールします。

In [1]:
# JupyterLite 用のパッケージインストール
try:
    import piplite
    await piplite.install(['numpy'])
except ImportError:
    pass

import numpy as np
print(f'NumPy バージョン: {np.__version__}')

NumPy バージョン: 2.4.0


---
## 1. NumPy とは

NumPy（Numerical Python）は、Python で高速な数値計算を行うためのライブラリです。

### NumPy の特徴
- **ndarray**: 高速な多次元配列オブジェクト
- **ベクトル化演算**: ループを使わずに配列全体に演算を適用
- **ブロードキャスト**: 異なる形状の配列間での演算
- **線形代数・フーリエ変換・乱数生成**: 豊富な数学関数

In [2]:
# Python リストと NumPy 配列の速度比較
import time

# Python リストでの計算
python_list = list(range(1000000))
start = time.time()
result_list = [x * 2 for x in python_list]
python_time = time.time() - start

# NumPy 配列での計算
numpy_array = np.arange(1000000)
start = time.time()
result_array = numpy_array * 2
numpy_time = time.time() - start

print(f'Python リスト: {python_time:.4f} 秒')
print(f'NumPy 配列: {numpy_time:.4f} 秒')
print(f'NumPy は約 {python_time / numpy_time:.1f} 倍高速')

Python リスト: 0.0673 秒
NumPy 配列: 0.0095 秒
NumPy は約 7.1 倍高速


---
## 2. 配列（ndarray）の作成

NumPy の中心となるデータ構造は `ndarray`（N-dimensional array）です。

### 2.1 リストから配列を作成

In [3]:
# 1次元配列
arr1d = np.array([1, 2, 3, 4, 5])
print('1次元配列:', arr1d)
print('型:', type(arr1d))

1次元配列: [1 2 3 4 5]
型: <class 'numpy.ndarray'>


In [4]:
# 2次元配列（行列）
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print('2次元配列:')
print(arr2d)

2次元配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# 3次元配列
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print('3次元配列:')
print(arr3d)
print('形状:', arr3d.shape)

3次元配列:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
形状: (2, 2, 2)


### 2.2 特殊な配列の作成

In [6]:
# ゼロ配列
zeros = np.zeros((3, 4))
print('ゼロ配列 (3x4):')
print(zeros)

ゼロ配列 (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 1で満たされた配列
ones = np.ones((2, 3))
print('1の配列 (2x3):')
print(ones)

1の配列 (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 任意の値で満たされた配列
full = np.full((2, 2), 7)
print('7で満たされた配列:')
print(full)

7で満たされた配列:
[[7 7]
 [7 7]]


In [9]:
# 単位行列
identity = np.eye(3)
print('単位行列 (3x3):')
print(identity)

単位行列 (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 対角行列
diag = np.diag([1, 2, 3, 4])
print('対角行列:')
print(diag)

対角行列:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 2.3 数列の生成

In [11]:
# arange: 等差数列（終点を含まない）
arr_range = np.arange(0, 10, 2)  # 0から10未満まで、2刻み
print('arange(0, 10, 2):', arr_range)

arange(0, 10, 2): [0 2 4 6 8]


In [12]:
# linspace: 等間隔の数列（終点を含む）
arr_lin = np.linspace(0, 1, 5)  # 0から1まで5個の等間隔
print('linspace(0, 1, 5):', arr_lin)

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [13]:
# logspace: 対数スケールの等間隔
arr_log = np.logspace(0, 3, 4)  # 10^0 から 10^3 まで4個
print('logspace(0, 3, 4):', arr_log)

logspace(0, 3, 4): [   1.   10.  100. 1000.]


### 2.4 乱数による配列生成

In [14]:
# 乱数シードの設定（再現性のため）
np.random.seed(42)

# 一様乱数 [0, 1)
uniform = np.random.rand(3, 3)
print('一様乱数 (3x3):')
print(uniform)

一様乱数 (3x3):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [15]:
# 標準正規乱数
normal = np.random.randn(3, 3)
print('標準正規乱数 (3x3):')
print(normal)

標準正規乱数 (3x3):
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]


In [16]:
# 整数乱数
integers = np.random.randint(1, 100, size=(3, 4))
print('整数乱数 1-99 (3x4):')
print(integers)

整数乱数 1-99 (3x4):
[[80 15 62 62]
 [47 62 51 55]
 [64  3 51  7]]


### 📝 2章 練習問題

1. 5x5 のゼロ行列を作成し、対角成分を 1, 2, 3, 4, 5 に設定してください
2. 0 から 100 まで 11 個の等間隔の数列を作成してください

In [17]:
# 練習問題の解答欄



---
## 3. 配列の属性

ndarray には様々な属性があります。

In [18]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print('配列:')
print(arr)
print()
print(f'shape (形状): {arr.shape}')       # 行数 x 列数
print(f'ndim (次元数): {arr.ndim}')       # 次元の数
print(f'size (要素数): {arr.size}')       # 全要素数
print(f'dtype (データ型): {arr.dtype}')  # データ型

配列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape (形状): (3, 4)
ndim (次元数): 2
size (要素数): 12
dtype (データ型): int64


In [19]:
# データ型の指定
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_int = np.array([1.5, 2.7, 3.9], dtype=np.int32)
arr_complex = np.array([1, 2, 3], dtype=np.complex128)

print(f'float64: {arr_float}, dtype: {arr_float.dtype}')
print(f'int32: {arr_int}, dtype: {arr_int.dtype}')  # 小数点以下は切り捨て
print(f'complex128: {arr_complex}, dtype: {arr_complex.dtype}')

float64: [1. 2. 3.], dtype: float64
int32: [1 2 3], dtype: int32
complex128: [1.+0.j 2.+0.j 3.+0.j], dtype: complex128


---
## 4. インデックスとスライス

配列の要素にアクセスする方法を学びます。

### 4.1 1次元配列のインデックス

In [20]:
arr = np.array([10, 20, 30, 40, 50])
print('配列:', arr)
print(f'arr[0] = {arr[0]}')    # 最初の要素
print(f'arr[-1] = {arr[-1]}')  # 最後の要素
print(f'arr[1:4] = {arr[1:4]}')  # インデックス 1 から 3 まで

配列: [10 20 30 40 50]
arr[0] = 10
arr[-1] = 50
arr[1:4] = [20 30 40]


### 4.2 2次元配列のインデックス

In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print('2次元配列:')
print(arr2d)
print()
print(f'arr2d[0, 0] = {arr2d[0, 0]}')  # 1行1列目
print(f'arr2d[1, 2] = {arr2d[1, 2]}')  # 2行3列目
print(f'arr2d[2] = {arr2d[2]}')        # 3行目全体

2次元配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[0, 0] = 1
arr2d[1, 2] = 6
arr2d[2] = [7 8 9]


### 4.3 スライス

In [22]:
arr2d = np.arange(1, 17).reshape(4, 4)
print('元の配列:')
print(arr2d)
print()

# 行のスライス
print('最初の2行:')
print(arr2d[:2])
print()

# 列のスライス
print('最初の2列:')
print(arr2d[:, :2])
print()

# 部分行列
print('中央の 2x2 部分:')
print(arr2d[1:3, 1:3])

元の配列:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

最初の2行:
[[1 2 3 4]
 [5 6 7 8]]

最初の2列:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

中央の 2x2 部分:
[[ 6  7]
 [10 11]]


### 4.4 ブールインデックス

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('元の配列:', arr)

# 条件を満たす要素を抽出
mask = arr > 5
print('mask (arr > 5):', mask)
print('5より大きい要素:', arr[mask])

# 複数条件
print('3以上7以下の要素:', arr[(arr >= 3) & (arr <= 7)])

元の配列: [ 1  2  3  4  5  6  7  8  9 10]
mask (arr > 5): [False False False False False  True  True  True  True  True]
5より大きい要素: [ 6  7  8  9 10]
3以上7以下の要素: [3 4 5 6 7]


### 4.5 ファンシーインデックス

In [24]:
arr = np.array([10, 20, 30, 40, 50])

# インデックスのリストで複数要素を取得
indices = [0, 2, 4]
print('arr[[0, 2, 4]]:', arr[indices])

# 2次元配列でのファンシーインデックス
arr2d = np.arange(1, 10).reshape(3, 3)
print('\n2次元配列:')
print(arr2d)
print('\narr2d[[0, 2], [1, 2]]:', arr2d[[0, 2], [1, 2]])  # (0,1) と (2,2) の要素

arr[[0, 2, 4]]: [10 30 50]

2次元配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[[0, 2], [1, 2]]: [2 9]


### 📝 4章 練習問題

以下の配列から指定された要素を抽出してください。

```python
arr = np.arange(1, 26).reshape(5, 5)
```

1. 3行目全体
2. 最後の列
3. 偶数の要素のみ
4. 右下の 3x3 部分行列

In [25]:
# 練習問題の解答欄
arr = np.arange(1, 26).reshape(5, 5)
print('元の配列:')
print(arr)


元の配列:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


---
## 5. 配列の演算

NumPy の配列演算は要素ごと（element-wise）に行われます。

### 5.1 算術演算

In [26]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(f'a = {a}')
print(f'b = {b}')
print(f'a + b = {a + b}')  # 加算
print(f'a - b = {a - b}')  # 減算
print(f'a * b = {a * b}')  # 乗算（要素ごと）
print(f'b / a = {b / a}')  # 除算
print(f'a ** 2 = {a ** 2}')  # べき乗

a = [1 2 3 4]
b = [10 20 30 40]
a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]


### 5.2 スカラーとの演算

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print(f'arr = {arr}')
print(f'arr + 10 = {arr + 10}')
print(f'arr * 2 = {arr * 2}')
print(f'arr / 2 = {arr / 2}')

arr = [1 2 3 4 5]
arr + 10 = [11 12 13 14 15]
arr * 2 = [ 2  4  6  8 10]
arr / 2 = [0.5 1.  1.5 2.  2.5]


### 5.3 ブロードキャスト

異なる形状の配列間で演算を行う仕組みです。

In [28]:
# 2次元配列と1次元配列の演算
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr1d = np.array([10, 20, 30])

print('2次元配列:')
print(arr2d)
print('\n1次元配列:', arr1d)
print('\n2次元 + 1次元（各行に加算）:')
print(arr2d + arr1d)

2次元配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1次元配列: [10 20 30]

2次元 + 1次元（各行に加算）:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [29]:
# 列ベクトルとの演算
col_vec = np.array([[100], [200], [300]])
print('2次元配列:')
print(arr2d)
print('\n列ベクトル:')
print(col_vec)
print('\n2次元 + 列ベクトル（各列に加算）:')
print(arr2d + col_vec)

2次元配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

列ベクトル:
[[100]
 [200]
 [300]]

2次元 + 列ベクトル（各列に加算）:
[[101 102 103]
 [204 205 206]
 [307 308 309]]


### 5.4 比較演算

In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(f'arr = {arr}')
print(f'arr > 3: {arr > 3}')
print(f'arr == 3: {arr == 3}')
print(f'arr != 3: {arr != 3}')

arr = [1 2 3 4 5]
arr > 3: [False False False  True  True]
arr == 3: [False False  True False False]
arr != 3: [ True  True False  True  True]


---
## 6. ユニバーサル関数（ufunc）

配列の各要素に対して高速に演算を行う関数です。

### 6.1 数学関数

In [31]:
arr = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print('角度（ラジアン）:', arr)
print('sin:', np.sin(arr))
print('cos:', np.cos(arr))
print('tan:', np.tan(arr[:4]))  # π/2 は除外

角度（ラジアン）: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: [0.         0.57735027 1.         1.73205081]


In [32]:
arr = np.array([1, 2, 3, 4, 5])

print('元の配列:', arr)
print('平方根:', np.sqrt(arr))
print('指数関数:', np.exp(arr))
print('自然対数:', np.log(arr))
print('常用対数:', np.log10(arr))

元の配列: [1 2 3 4 5]
平方根: [1.         1.41421356 1.73205081 2.         2.23606798]
指数関数: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
自然対数: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
常用対数: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


### 6.2 丸め関数

In [33]:
arr = np.array([1.2, 2.5, 3.7, -1.2, -2.5, -3.7])

print('元の配列:', arr)
print('四捨五入:', np.round(arr))
print('切り捨て:', np.floor(arr))
print('切り上げ:', np.ceil(arr))
print('ゼロ方向への切り捨て:', np.trunc(arr))

元の配列: [ 1.2  2.5  3.7 -1.2 -2.5 -3.7]
四捨五入: [ 1.  2.  4. -1. -2. -4.]
切り捨て: [ 1.  2.  3. -2. -3. -4.]
切り上げ: [ 2.  3.  4. -1. -2. -3.]
ゼロ方向への切り捨て: [ 1.  2.  3. -1. -2. -3.]


### 6.3 集約関数

In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print('配列:')
print(arr)
print()

print(f'全要素の合計: {np.sum(arr)}')
print(f'行ごとの合計: {np.sum(arr, axis=1)}')
print(f'列ごとの合計: {np.sum(arr, axis=0)}')
print()
print(f'全要素の積: {np.prod(arr)}')
print(f'累積和: {np.cumsum(arr.flatten())}')

配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

全要素の合計: 45
行ごとの合計: [ 6 15 24]
列ごとの合計: [12 15 18]

全要素の積: 362880
累積和: [ 1  3  6 10 15 21 28 36 45]


---
## 7. 基本的な統計関数

NumPy には基本的な統計計算のための関数が用意されています。

In [35]:
np.random.seed(42)
data = np.random.randn(100)  # 標準正規分布からのサンプル

print('--- 基本統計量 ---')
print(f'平均: {np.mean(data):.4f}')
print(f'中央値: {np.median(data):.4f}')
print(f'標準偏差: {np.std(data):.4f}')
print(f'分散: {np.var(data):.4f}')
print(f'最小値: {np.min(data):.4f}')
print(f'最大値: {np.max(data):.4f}')

--- 基本統計量 ---
平均: -0.1038
中央値: -0.1270
標準偏差: 0.9036
分散: 0.8165
最小値: -2.6197
最大値: 1.8523


In [36]:
# パーセンタイル
print('--- パーセンタイル ---')
print(f'25%点: {np.percentile(data, 25):.4f}')
print(f'50%点: {np.percentile(data, 50):.4f}')
print(f'75%点: {np.percentile(data, 75):.4f}')

--- パーセンタイル ---
25%点: -0.6009
50%点: -0.1270
75%点: 0.4060


In [37]:
# 2次元配列での軸指定
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print('配列:')
print(arr2d)
print()
print(f'各列の平均: {np.mean(arr2d, axis=0)}')
print(f'各行の平均: {np.mean(arr2d, axis=1)}')
print(f'各列の標準偏差: {np.std(arr2d, axis=0)}')

配列:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

各列の平均: [4. 5. 6.]
各行の平均: [2. 5. 8.]
各列の標準偏差: [2.44948974 2.44948974 2.44948974]


In [38]:
# 相関係数と共分散
np.random.seed(42)
x = np.random.randn(50)
y = 2 * x + np.random.randn(50) * 0.5  # x と相関のあるデータ

print('相関係数行列:')
print(np.corrcoef(x, y))
print()
print('共分散行列:')
print(np.cov(x, y))

相関係数行列:
[[1.         0.97522354]
 [0.97522354 1.        ]]

共分散行列:
[[0.87173739 1.78840224]
 [1.78840224 3.85777041]]


### 📝 7章 練習問題

以下のデータについて統計量を計算してください。

```python
scores = np.array([78, 85, 92, 67, 88, 95, 72, 81, 89, 76])
```

1. 平均点、中央値、標準偏差を計算
2. 最高点と最低点、およびその差（レンジ）を求める
3. 80点以上の人数を数える

In [39]:
# 練習問題の解答欄
scores = np.array([78, 85, 92, 67, 88, 95, 72, 81, 89, 76])


---
## 8. 配列の形状操作

配列の形を変更する様々な方法を学びます。

### 8.1 reshape

In [40]:
arr = np.arange(12)
print('元の配列:', arr)
print()

# 3行4列に変形
reshaped = arr.reshape(3, 4)
print('reshape(3, 4):')
print(reshaped)
print()

# -1 を使うと自動計算
reshaped2 = arr.reshape(4, -1)
print('reshape(4, -1):')
print(reshaped2)

元の配列: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(4, -1):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 8.2 flatten と ravel

In [41]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print('元の配列:')
print(arr2d)
print()

# flatten: コピーを返す
flat = arr2d.flatten()
print('flatten():', flat)

# ravel: 可能ならビューを返す
rav = arr2d.ravel()
print('ravel():', rav)

元の配列:
[[1 2 3]
 [4 5 6]]

flatten(): [1 2 3 4 5 6]
ravel(): [1 2 3 4 5 6]


### 8.3 転置

In [42]:
arr = np.arange(6).reshape(2, 3)
print('元の配列 (2x3):')
print(arr)
print()

print('転置 (3x2):')
print(arr.T)

元の配列 (2x3):
[[0 1 2]
 [3 4 5]]

転置 (3x2):
[[0 3]
 [1 4]
 [2 5]]


### 8.4 配列の結合

In [43]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('配列 a:')
print(a)
print('\n配列 b:')
print(b)

# 縦方向に結合（行を追加）
print('\nvstack (縦結合):')
print(np.vstack([a, b]))

# 横方向に結合（列を追加）
print('\nhstack (横結合):')
print(np.hstack([a, b]))

配列 a:
[[1 2]
 [3 4]]

配列 b:
[[5 6]
 [7 8]]

vstack (縦結合):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (横結合):
[[1 2 5 6]
 [3 4 7 8]]


In [44]:
# concatenate: 軸を指定して結合
print('concatenate (axis=0):')
print(np.concatenate([a, b], axis=0))

print('\nconcatenate (axis=1):')
print(np.concatenate([a, b], axis=1))

concatenate (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate (axis=1):
[[1 2 5 6]
 [3 4 7 8]]


### 8.5 配列の分割

In [45]:
arr = np.arange(16).reshape(4, 4)
print('元の配列:')
print(arr)
print()

# 縦方向に分割
top, bottom = np.vsplit(arr, 2)
print('vsplit (上半分):')
print(top)
print('\nvsplit (下半分):')
print(bottom)

元の配列:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

vsplit (上半分):
[[0 1 2 3]
 [4 5 6 7]]

vsplit (下半分):
[[ 8  9 10 11]
 [12 13 14 15]]


In [46]:
# 横方向に分割
left, right = np.hsplit(arr, 2)
print('hsplit (左半分):')
print(left)
print('\nhsplit (右半分):')
print(right)

hsplit (左半分):
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

hsplit (右半分):
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


---
## まとめ

このチュートリアルで学んだことをまとめます：

| トピック | 主な関数・操作 |
|---------|---------------|
| 配列の作成 | `array()`, `zeros()`, `ones()`, `arange()`, `linspace()` |
| 配列の属性 | `shape`, `ndim`, `size`, `dtype` |
| インデックス | `arr[i]`, `arr[i, j]`, スライス, ブールインデックス |
| 算術演算 | `+`, `-`, `*`, `/`, `**`（要素ごと） |
| ユニバーサル関数 | `sin()`, `cos()`, `sqrt()`, `exp()`, `log()` |
| 統計関数 | `mean()`, `std()`, `var()`, `min()`, `max()`, `sum()` |
| 形状操作 | `reshape()`, `flatten()`, `T`, `vstack()`, `hstack()` |

## 次のステップ

初級を終えたら、**NumPy 中級チュートリアル** で以下を学びましょう：
- 高度なインデックス操作
- ブロードキャストの詳細
- 線形代数（行列演算）
- 構造化配列
- メモリ効率とパフォーマンス

---
## 総合演習

これまで学んだ内容を使って、以下の課題に挑戦してください。

### 課題：売上データの分析

1. 以下のデータを NumPy 配列として作成しなさい：
   - 5つの店舗（A〜E）の 7日間の売上データ（5行7列の行列）
   - 乱数で生成し、値は 10000〜50000 の範囲の整数

2. 以下の統計量を計算しなさい：
   - 全体の売上合計と平均
   - 各店舗の売上合計（行ごとの合計）
   - 各曜日の売上合計（列ごとの合計）

3. 以下のフィルタリングを行いなさい：
   - 売上が 30000 を超えたセルの数
   - 最も売上が高かった店舗と曜日

4. データの変形を行いなさい：
   - 配列を 1次元に展開
   - 転置して曜日×店舗の形に変換

In [47]:
# 総合演習の解答欄

