# JupyterLite で学ぶ NumPy 中級チュートリアル

このノートブックは、**JupyterLite（ブラウザだけで動く Jupyter 環境）** 上で、
NumPy の中級レベルの機能を学ぶためのチュートリアルです。

## 対象者
- NumPy の基礎（配列作成、インデックス、基本演算）を理解している方
- 線形代数やパフォーマンス最適化を学びたい方

## このチュートリアルで学ぶこと
1. 線形代数演算
2. 高度なインデックス操作
3. ブロードキャストの詳細
4. 構造化配列
5. メモリレイアウトとビュー
6. ベクトル化とパフォーマンス
7. ファイル入出力
8. 乱数生成（新API）

## 0. 環境準備（JupyterLite 用）

まず、必要なライブラリをインストールします。

In [1]:
# JupyterLite 用のパッケージインストール
try:
    import piplite
    await piplite.install(['numpy'])
except ImportError:
    pass

import numpy as np
print(f'NumPy バージョン: {np.__version__}')

NumPy バージョン: 2.4.6


---
## 1. 線形代数演算

NumPy の `linalg` モジュールは線形代数の基本演算を提供します。

### 1.1 行列の積

In [2]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print('行列 A:')
print(A)
print('\n行列 B:')
print(B)

# 要素ごとの積（アダマール積）
print('\n要素ごとの積 (A * B):')
print(A * B)

# 行列の積
print('\n行列の積 (A @ B):')
print(A @ B)

# np.dot も使える
print('\nnp.dot(A, B):')
print(np.dot(A, B))

行列 A:
[[1 2]
 [3 4]]

行列 B:
[[5 6]
 [7 8]]

要素ごとの積 (A * B):
[[ 5 12]
 [21 32]]

行列の積 (A @ B):
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]


### 1.2 ベクトルの内積・外積

In [3]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# 内積
print(f'v1 = {v1}')
print(f'v2 = {v2}')
print(f'内積 (v1 · v2): {np.dot(v1, v2)}')
print(f'内積 (v1 @ v2): {v1 @ v2}')

# 外積（3次元ベクトル）
print(f'外積 (v1 × v2): {np.cross(v1, v2)}')

# 外積（テンソル積）
print('\n外積（テンソル積）:')
print(np.outer(v1, v2))

v1 = [1 2 3]
v2 = [4 5 6]
内積 (v1 · v2): 32
内積 (v1 @ v2): 32
外積 (v1 × v2): [-3  6 -3]

外積（テンソル積）:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### 1.3 行列式と逆行列

In [4]:
A = np.array([[1, 2],
              [3, 4]])

print('行列 A:')
print(A)

# 行列式
det = np.linalg.det(A)
print(f'\n行列式: {det:.4f}')

# 逆行列
A_inv = np.linalg.inv(A)
print('\n逆行列:')
print(A_inv)

# 検証: A @ A_inv = I
print('\nA @ A_inv (単位行列になるはず):')
print(np.round(A @ A_inv, 10))

行列 A:
[[1 2]
 [3 4]]

行列式: -2.0000

逆行列:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (単位行列になるはず):
[[1. 0.]
 [0. 1.]]


### 1.4 固有値と固有ベクトル

In [5]:
A = np.array([[4, 2],
              [1, 3]])

print('行列 A:')
print(A)

# 固有値と固有ベクトル
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f'\n固有値: {eigenvalues}')
print('固有ベクトル（列ごと）:')
print(eigenvectors)

# 検証: A @ v = λ @ v
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lam = eigenvalues[i]
    print(f'\n固有値 {lam:.4f} の検証:')
    print(f'  A @ v = {A @ v}')
    print(f'  λ * v = {lam * v}')

行列 A:
[[4 2]
 [1 3]]

固有値: [5. 2.]
固有ベクトル（列ごと）:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

固有値 5.0000 の検証:
  A @ v = [4.47213595 2.23606798]
  λ * v = [4.47213595 2.23606798]

固有値 2.0000 の検証:
  A @ v = [-1.41421356  1.41421356]
  λ * v = [-1.41421356  1.41421356]


### 1.5 連立方程式の解法

In [6]:
# 連立方程式: Ax = b
# 2x + y = 5
# x + 3y = 7

A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 7])

# 解を求める
x = np.linalg.solve(A, b)
print('連立方程式 Ax = b の解:')
print(f'x = {x}')

# 検証
print(f'\n検証 (A @ x): {A @ x}')
print(f'b: {b}')

連立方程式 Ax = b の解:
x = [1.6 1.8]

検証 (A @ x): [5. 7.]
b: [5 7]


### 1.6 特異値分解（SVD）

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print('行列 A:')
print(A)

# 特異値分解
U, s, Vt = np.linalg.svd(A)

print('\nU (左特異ベクトル):')
print(U)
print(f'\n特異値: {s}')
print('\nVt (右特異ベクトルの転置):')
print(Vt)

# 復元: A = U @ S @ Vt
S = np.zeros_like(A, dtype=float)
S[:len(s), :len(s)] = np.diag(s)
A_reconstructed = U @ S @ Vt
print('\n復元された行列:')
print(np.round(A_reconstructed, 10))

行列 A:
[[1 2 3]
 [4 5 6]]

U (左特異ベクトル):
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

特異値: [9.508032   0.77286964]

Vt (右特異ベクトルの転置):
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]

復元された行列:
[[1. 2. 3.]
 [4. 5. 6.]]


### 1.7 ノルム

In [8]:
v = np.array([3, 4])
A = np.array([[1, 2],
              [3, 4]])

print(f'ベクトル v = {v}')
print(f'L2ノルム（ユークリッド）: {np.linalg.norm(v)}')
print(f'L1ノルム: {np.linalg.norm(v, ord=1)}')
print(f'無限大ノルム: {np.linalg.norm(v, ord=np.inf)}')

print('\n行列 A:')
print(A)
print(f'フロベニウスノルム: {np.linalg.norm(A)}')
print(f'行列の最大ノルム: {np.linalg.norm(A, ord=np.inf)}')

ベクトル v = [3 4]
L2ノルム（ユークリッド）: 5.0
L1ノルム: 7.0
無限大ノルム: 4.0

行列 A:
[[1 2]
 [3 4]]
フロベニウスノルム: 5.477225575051661
行列の最大ノルム: 7.0


### 📝 1章 練習問題

以下の連立方程式を解いてください。

```
x + 2y + 3z = 14
4x + 5y + 6z = 32
7x + 8y + 10z = 53
```

In [9]:
# 練習問題の解答欄



---
## 2. 高度なインデックス操作

### 2.1 np.where

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 条件を満たす要素のインデックスを取得
indices = np.where(arr > 5)
print(f'arr > 5 のインデックス: {indices[0]}')

# 条件に応じて値を選択（三項演算子的な使い方）
result = np.where(arr > 5, arr * 10, arr)
print(f'5より大きければ10倍、そうでなければそのまま: {result}')

arr > 5 のインデックス: [5 6 7 8 9]
5より大きければ10倍、そうでなければそのまま: [  1   2   3   4   5  60  70  80  90 100]


### 2.2 np.select

In [11]:
# 複数条件での選択
scores = np.array([45, 65, 75, 85, 95])

conditions = [
    scores >= 90,
    scores >= 80,
    scores >= 70,
    scores >= 60
]
choices = ['A', 'B', 'C', 'D']

grades = np.select(conditions, choices, default='F')
print(f'点数: {scores}')
print(f'成績: {grades}')

点数: [45 65 75 85 95]
成績: ['F' 'D' 'C' 'B' 'A']


### 2.3 np.take と np.put

In [12]:
arr = np.array([10, 20, 30, 40, 50])

# 指定インデックスの要素を取得
indices = [0, 2, 4]
print(f'np.take: {np.take(arr, indices)}')

# 指定インデックスに値を設定
arr_copy = arr.copy()
np.put(arr_copy, [1, 3], [200, 400])
print(f'np.put後: {arr_copy}')

np.take: [10 30 50]
np.put後: [ 10 200  30 400  50]


### 2.4 np.argmax, np.argmin, np.argsort

In [13]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(f'配列: {arr}')
print(f'最大値のインデックス: {np.argmax(arr)}')
print(f'最小値のインデックス: {np.argmin(arr)}')
print(f'ソート後のインデックス: {np.argsort(arr)}')
print(f'ソートされた配列: {arr[np.argsort(arr)]}')

配列: [3 1 4 1 5 9 2 6]
最大値のインデックス: 5
最小値のインデックス: 1
ソート後のインデックス: [1 3 6 0 2 4 7 5]
ソートされた配列: [1 1 2 3 4 5 6 9]


In [14]:
# 2次元配列での軸指定
arr2d = np.array([[3, 7, 2],
                  [8, 1, 5],
                  [4, 6, 9]])

print('2次元配列:')
print(arr2d)
print(f'\n各列の最大値のインデックス: {np.argmax(arr2d, axis=0)}')
print(f'各行の最大値のインデックス: {np.argmax(arr2d, axis=1)}')

2次元配列:
[[3 7 2]
 [8 1 5]
 [4 6 9]]

各列の最大値のインデックス: [1 0 2]
各行の最大値のインデックス: [1 0 2]


### 2.5 np.nonzero と np.flatnonzero

In [15]:
arr = np.array([0, 1, 0, 2, 0, 3, 0])

# 非ゼロ要素のインデックス
print(f'配列: {arr}')
print(f'非ゼロ要素のインデックス: {np.nonzero(arr)}')
print(f'flatnonzero: {np.flatnonzero(arr)}')

# 2次元配列
arr2d = np.array([[0, 1, 0],
                  [2, 0, 3]])
rows, cols = np.nonzero(arr2d)
print(f'\n2次元での非ゼロ位置:')
print(f'  行: {rows}')
print(f'  列: {cols}')

配列: [0 1 0 2 0 3 0]
非ゼロ要素のインデックス: (array([1, 3, 5]),)
flatnonzero: [1 3 5]

2次元での非ゼロ位置:
  行: [0 1 1]
  列: [1 0 2]


---
## 3. ブロードキャストの詳細

ブロードキャストのルールを詳しく理解しましょう。

### 3.1 ブロードキャストのルール

1. 次元数が異なる場合、少ない方の形状の先頭に 1 を追加
2. 各次元のサイズが同じか、どちらかが 1 の場合にブロードキャスト可能
3. サイズが 1 の次元は、もう一方のサイズに拡張される

In [16]:
# 例1: (3, 3) と (3,) → (3, 3)
A = np.ones((3, 3))
b = np.array([1, 2, 3])

print('A の形状:', A.shape)
print('b の形状:', b.shape)
print('\nA + b:')
print(A + b)

A の形状: (3, 3)
b の形状: (3,)

A + b:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [17]:
# 例2: (3, 1) と (1, 4) → (3, 4)
a = np.array([[1], [2], [3]])  # (3, 1)
b = np.array([[10, 20, 30, 40]])  # (1, 4)

print('a の形状:', a.shape)
print('b の形状:', b.shape)
print('\na + b:')
print(a + b)

a の形状: (3, 1)
b の形状: (1, 4)

a + b:
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [18]:
# np.newaxis を使った次元追加
arr = np.array([1, 2, 3])
print(f'元の形状: {arr.shape}')

row_vec = arr[np.newaxis, :]  # (1, 3)
col_vec = arr[:, np.newaxis]  # (3, 1)

print(f'行ベクトル: {row_vec.shape}')
print(f'列ベクトル: {col_vec.shape}')

# 外積を計算
print('\n外積 (col @ row):')
print(col_vec * row_vec)

元の形状: (3,)
行ベクトル: (1, 3)
列ベクトル: (3, 1)

外積 (col @ row):
[[1 2 3]
 [2 4 6]
 [3 6 9]]


### 3.2 broadcast_to と broadcast_arrays

In [19]:
# 配列を指定の形状にブロードキャスト
arr = np.array([1, 2, 3])
broadcasted = np.broadcast_to(arr, (4, 3))
print('ブロードキャスト結果 (4, 3):')
print(broadcasted)

ブロードキャスト結果 (4, 3):
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
# 複数配列を共通の形状にブロードキャスト
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

a_bc, b_bc = np.broadcast_arrays(a, b)
print('a をブロードキャスト:')
print(a_bc)
print('\nb をブロードキャスト:')
print(b_bc)

a をブロードキャスト:
[[1 1 1]
 [2 2 2]
 [3 3 3]]

b をブロードキャスト:
[[10 20 30]
 [10 20 30]
 [10 20 30]]


---
## 4. 構造化配列

異なるデータ型を持つフィールドを含む配列です。

In [21]:
# 構造化データ型の定義
dt = np.dtype([('name', 'U10'),    # Unicode文字列（最大10文字）
               ('age', 'i4'),       # 32ビット整数
               ('height', 'f8')])   # 64ビット浮動小数点

# データの作成
data = np.array([('Alice', 25, 165.5),
                 ('Bob', 30, 178.2),
                 ('Charlie', 35, 172.0)],
                dtype=dt)

print('構造化配列:')
print(data)
print(f'\nデータ型: {data.dtype}')

構造化配列:
[('Alice', 25, 165.5) ('Bob', 30, 178.2) ('Charlie', 35, 172. )]

データ型: [('name', '<U10'), ('age', '<i4'), ('height', '<f8')]


In [22]:
# フィールドへのアクセス
print(f'名前: {data["name"]}')
print(f'年齢: {data["age"]}')
print(f'身長: {data["height"]}')

# フィルタリング
print(f'\n30歳以上: {data[data["age"] >= 30]}')

名前: ['Alice' 'Bob' 'Charlie']
年齢: [25 30 35]
身長: [165.5 178.2 172. ]

30歳以上: [('Bob', 30, 178.2) ('Charlie', 35, 172. )]


In [23]:
# レコードへのアクセス
print('最初のレコード:', data[0])
print('最初のレコードの名前:', data[0]['name'])

# ソート
sorted_by_age = np.sort(data, order='age')
print('\n年齢でソート:')
print(sorted_by_age)

最初のレコード: ('Alice', 25, 165.5)
最初のレコードの名前: Alice

年齢でソート:
[('Alice', 25, 165.5) ('Bob', 30, 178.2) ('Charlie', 35, 172. )]


---
## 5. メモリレイアウトとビュー

### 5.1 C順序とFortran順序

In [24]:
# C順序（行優先）とFortran順序（列優先）
arr_c = np.array([[1, 2, 3],
                  [4, 5, 6]], order='C')  # C順序（デフォルト）
arr_f = np.array([[1, 2, 3],
                  [4, 5, 6]], order='F')  # Fortran順序

print('C順序のメモリレイアウト:', arr_c.ravel('K'))
print('Fortran順序のメモリレイアウト:', arr_f.ravel('K'))

print(f'\narr_c.flags.c_contiguous: {arr_c.flags.c_contiguous}')
print(f'arr_f.flags.f_contiguous: {arr_f.flags.f_contiguous}')

C順序のメモリレイアウト: [1 2 3 4 5 6]
Fortran順序のメモリレイアウト: [1 4 2 5 3 6]

arr_c.flags.c_contiguous: True
arr_f.flags.f_contiguous: True


### 5.2 ビューとコピー

In [25]:
original = np.array([1, 2, 3, 4, 5])

# ビュー（元のデータを共有）
view = original[1:4]
view[0] = 100
print(f'ビューを変更後の元配列: {original}')

# コピー（独立したデータ）
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 100
print(f'コピーを変更後の元配列: {original}')

ビューを変更後の元配列: [  1 100   3   4   5]
コピーを変更後の元配列: [1 2 3 4 5]


In [26]:
# ビューかどうかを確認
original = np.array([[1, 2, 3],
                     [4, 5, 6]])

slice_view = original[:, 0]  # ビュー
fancy_copy = original[[0, 1], 0]  # コピー（ファンシーインデックス）

print(f'スライスはビュー: {slice_view.base is original}')
print(f'ファンシーインデックスはコピー: {fancy_copy.base is None}')

スライスはビュー: True
ファンシーインデックスはコピー: True


### 5.3 strides

In [27]:
arr = np.arange(12).reshape(3, 4)

print('配列:')
print(arr)
print(f'\n形状: {arr.shape}')
print(f'ストライド: {arr.strides}')  # 次の要素/行に移動するためのバイト数
print(f'要素サイズ: {arr.itemsize} バイト')

配列:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

形状: (3, 4)
ストライド: (32, 8)
要素サイズ: 8 バイト


---
## 6. ベクトル化とパフォーマンス

### 6.1 ループ vs ベクトル化

In [28]:
import time

# サンプルデータ
np.random.seed(42)
data = np.random.randn(100000)

# ループによる計算
def loop_sum_squares(arr):
    result = 0
    for x in arr:
        result += x ** 2
    return result

start = time.time()
result_loop = loop_sum_squares(data)
time_loop = time.time() - start

# ベクトル化による計算
start = time.time()
result_vectorized = np.sum(data ** 2)
time_vectorized = time.time() - start

print(f'ループ: {time_loop:.6f} 秒')
print(f'ベクトル化: {time_vectorized:.6f} 秒')
print(f'高速化率: {time_loop / time_vectorized:.1f}倍')

ループ: 0.020452 秒
ベクトル化: 0.002118 秒
高速化率: 9.7倍


### 6.2 np.vectorize

In [29]:
# スカラー関数を配列対応に変換
def scalar_func(x):
    if x < 0:
        return 0
    elif x < 1:
        return x
    else:
        return 1

# vectorize でラップ
vectorized_func = np.vectorize(scalar_func)

arr = np.array([-0.5, 0.3, 0.7, 1.2, 2.0])
result = vectorized_func(arr)
print(f'入力: {arr}')
print(f'出力: {result}')

入力: [-0.5  0.3  0.7  1.2  2. ]
出力: [0 0 0 1 1]


### 6.3 np.einsum（アインシュタイン縮約記法）

In [30]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 行列の積
print('行列の積 (ij,jk->ik):')
print(np.einsum('ij,jk->ik', A, B))

# 要素ごとの積
print('\n要素ごとの積 (ij,ij->ij):')
print(np.einsum('ij,ij->ij', A, B))

# トレース（対角成分の和）
print(f'\nトレース (ii->): {np.einsum("ii->", A)}')

# 転置
print('\n転置 (ij->ji):')
print(np.einsum('ij->ji', A))

行列の積 (ij,jk->ik):
[[19 22]
 [43 50]]

要素ごとの積 (ij,ij->ij):
[[ 5 12]
 [21 32]]

トレース (ii->): 5

転置 (ij->ji):
[[1 3]
 [2 4]]


---
## 7. ファイル入出力

### 7.1 NumPy バイナリ形式

In [31]:
# 配列の保存（単一）
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# .npy 形式で保存
np.save('/tmp/array.npy', arr)

# 読み込み
loaded = np.load('/tmp/array.npy')
print('読み込んだ配列:')
print(loaded)

読み込んだ配列:
[[1 2 3]
 [4 5 6]]


In [32]:
# 複数配列の保存
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# .npz 形式で保存
np.savez('/tmp/arrays.npz', first=arr1, second=arr2)

# 読み込み
loaded = np.load('/tmp/arrays.npz')
print('first:', loaded['first'])
print('second:', loaded['second'])

first: [1 2 3]
second: [4 5 6]


### 7.2 テキスト形式

In [33]:
# テキストファイルとして保存
arr = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0]])

np.savetxt('/tmp/array.txt', arr, fmt='%.2f', delimiter=',')

# 読み込み
loaded = np.loadtxt('/tmp/array.txt', delimiter=',')
print('テキストから読み込み:')
print(loaded)

テキストから読み込み:
[[1. 2. 3.]
 [4. 5. 6.]]


In [34]:
# genfromtxt: より柔軟な読み込み（欠損値対応など）
# ヘッダー付きデータの例
data_str = """# x, y, z
1.0, 2.0, 3.0
4.0, , 6.0
7.0, 8.0, 9.0"""

# 文字列をファイルに書き込み
with open('/tmp/data_with_missing.csv', 'w') as f:
    f.write(data_str)

# genfromtxt で読み込み（欠損値を NaN として扱う）
data = np.genfromtxt('/tmp/data_with_missing.csv', 
                     delimiter=',', 
                     skip_header=1,
                     filling_values=np.nan)
print('欠損値を含むデータ:')
print(data)

欠損値を含むデータ:
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


---
## 8. 乱数生成（新API）

NumPy 1.17 以降で推奨される `Generator` ベースの乱数生成を学びます。

In [35]:
# Generator の作成
rng = np.random.default_rng(seed=42)

# 一様乱数 [0, 1)
print('一様乱数:')
print(rng.random((3, 3)))

一様乱数:
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


In [36]:
# 整数乱数
print('整数乱数 (0-9):')
print(rng.integers(0, 10, size=(3, 4)))

整数乱数 (0-9):
[[8 4 5 3]
 [1 9 7 6]
 [4 8 5 4]]


In [37]:
# 正規分布
print('正規分布 (平均=0, 標準偏差=1):')
print(rng.standard_normal((3, 3)))

print('\n正規分布 (平均=50, 標準偏差=10):')
print(rng.normal(loc=50, scale=10, size=(3, 3)))

正規分布 (平均=0, 標準偏差=1):
[[-0.85929246  0.36875078 -0.9588826 ]
 [ 0.8784503  -0.04992591 -0.18486236]
 [-0.68092954  1.22254134 -0.15452948]]

正規分布 (平均=50, 標準偏差=10):
[[45.71672178 46.4786645  55.32309186]
 [53.65444064 54.12732612 54.30821003]
 [71.41647601 45.93584984 44.87757271]]


In [38]:
# 様々な分布
rng = np.random.default_rng(42)

# 二項分布
binomial = rng.binomial(n=10, p=0.5, size=10)
print(f'二項分布 (n=10, p=0.5): {binomial}')

# ポアソン分布
poisson = rng.poisson(lam=5, size=10)
print(f'ポアソン分布 (λ=5): {poisson}')

# 指数分布
exponential = rng.exponential(scale=2.0, size=5)
print(f'指数分布 (scale=2): {exponential}')

二項分布 (n=10, p=0.5): [6 5 7 6 3 8 6 6 3 5]
ポアソン分布 (λ=5): [7 9 6 3 8 3 7 8 5 6]
指数分布 (scale=2): [0.2688345  0.28496167 0.23536464 0.10934624 3.43318638]


In [39]:
# シャッフルと選択
rng = np.random.default_rng(42)
arr = np.arange(10)

# シャッフル（インプレース）
arr_copy = arr.copy()
rng.shuffle(arr_copy)
print(f'シャッフル: {arr_copy}')

# シャッフルされたコピーを返す
permuted = rng.permutation(arr)
print(f'permutation: {permuted}')

# ランダム選択
choice = rng.choice(arr, size=5, replace=False)
print(f'ランダム選択（重複なし）: {choice}')

シャッフル: [5 6 0 7 3 2 4 9 1 8]
permutation: [4 8 2 6 5 9 7 3 0 1]
ランダム選択（重複なし）: [9 2 4 3 6]


### 📝 8章 練習問題

1. シード 123 の Generator を作成し、平均 100、標準偏差 15 の正規分布から 1000 個のサンプルを生成してください
2. そのサンプルの平均、標準偏差、最小値、最大値を計算してください
3. 70 以上 130 以下の値の割合を計算してください

In [40]:
# 練習問題の解答欄



---
## まとめ

このチュートリアルで学んだことをまとめます：

| トピック | 主な関数・操作 |
|---------|---------------|
| 線形代数 | `@`, `dot()`, `linalg.inv()`, `linalg.eig()`, `linalg.solve()` |
| 高度なインデックス | `where()`, `select()`, `argmax()`, `argsort()` |
| ブロードキャスト | `newaxis`, `broadcast_to()`, `broadcast_arrays()` |
| 構造化配列 | `dtype([...])`, フィールドアクセス |
| メモリ | ビューとコピー、`strides`, C/F順序 |
| パフォーマンス | ベクトル化、`vectorize()`, `einsum()` |
| ファイルI/O | `save()`, `load()`, `savetxt()`, `genfromtxt()` |
| 乱数（新API） | `default_rng()`, `Generator` メソッド |

## 次のステップ

NumPy の中級を終えたら、以下のライブラリも学んでみましょう：
- **pandas**: データ分析のための高機能データ構造
- **scipy**: 科学技術計算（最適化、積分、統計など）
- **scikit-learn**: 機械学習ライブラリ